
// This file was auto-generated by ML.NET Model Builder. 

using SentimentAnalysisModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
SentimentAnalysisModel.ModelInput sampleData = new SentimentAnalysisModel.ModelInput()
{
    TextID = @"549e992a42",
    Text = @"Sooo SAD I will miss you here in San Diego!!!",
    Selected_text = @"Sooo SAD",
    Time_of_Tweet = @"noon",
    Age_of_User = @"21-30",
    Country = @"Albania",
    Population_2020 = 2877797F,
    Land_Area_Km = 27400F,
    Density_P_Km = 105F,
};

// Make a single prediction on the sample data and print results
var predictionResult = SentimentAnalysisModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Sentiment with predicted Sentiment from sample data...\n\n");


Console.WriteLine($"TextID: {@"549e992a42"}");
Console.WriteLine($"Text: {@"Sooo SAD I will miss you here in San Diego!!!"}");
Console.WriteLine($"Selected_text: {@"Sooo SAD"}");
Console.WriteLine($"Sentiment: {@"negative"}");
Console.WriteLine($"Time_of_Tweet: {@"noon"}");
Console.WriteLine($"Age_of_User: {@"21-30"}");
Console.WriteLine($"Country: {@"Albania"}");
Console.WriteLine($"Population_2020: {2877797F}");
Console.WriteLine($"Land_Area_Km: {27400F}");
Console.WriteLine($"Density_P_Km: {105F}");


Console.WriteLine($"\n\nPredicted Sentiment: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

