// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SentimentAnalysisModel_ConsoleApp1
{
    public partial class SentimentAnalysisModel
    {
        /// <summary>
        /// model input class for SentimentAnalysisModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"textID")]
            public string TextID { get; set; }

            [ColumnName(@"text")]
            public string Text { get; set; }

            [ColumnName(@"selected_text")]
            public string Selected_text { get; set; }

            [ColumnName(@"sentiment")]
            public string Sentiment { get; set; }

            [ColumnName(@"Time_of_Tweet")]
            public string Time_of_Tweet { get; set; }

            [ColumnName(@"Age_of_User")]
            public string Age_of_User { get; set; }

            [ColumnName(@"Country")]
            public string Country { get; set; }

            [ColumnName(@"Population_2020")]
            public float Population_2020 { get; set; }

            [ColumnName(@"Land_Area_Km")]
            public float Land_Area_Km { get; set; }

            [ColumnName(@"Density_P_Km")]
            public float Density_P_Km { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SentimentAnalysisModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"textID")]
            public string TextID { get; set; }

            [ColumnName(@"text")]
            public string Text { get; set; }

            [ColumnName(@"selected_text")]
            public float[] Selected_text { get; set; }

            [ColumnName(@"sentiment")]
            public uint Sentiment { get; set; }

            [ColumnName(@"Time_of_Tweet")]
            public string Time_of_Tweet { get; set; }

            [ColumnName(@"Age_of_User")]
            public string Age_of_User { get; set; }

            [ColumnName(@"Country")]
            public string Country { get; set; }

            [ColumnName(@"Population_2020")]
            public float Population_2020 { get; set; }

            [ColumnName(@"Land_Area_Km")]
            public float Land_Area_Km { get; set; }

            [ColumnName(@"Density_P_Km")]
            public float Density_P_Km { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SentimentAnalysisModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
